### PR TITLE
#7 - Add additional commands

### PR DESCRIPTION
**Pull request by oscarmorrison**
The lack of commands for sublime-yuml is a little frustrating. If I am working and creating multiple different types of Diagrams at once having to go and change the default type each time is frustrating.

As such I have added additional commands to make diagrams of each type:
- Open Class Diagram in Browser  
- Open Activity Diagram in Browser  
- Open Usecase Diagram in Browser

### CODE REVIEW

**Comment by oscarmorrison** [comment]
@cluther @patrickayoup What do you think?

**Comment by patrickayoup** [comment]
@oscarmorrison Looks like a good idea to me. :+1:

**Comment by oscarmorrison** [comment]
@patrickayoup Updated Readme to include new image. 
Is this ready to merge?

**Comment by patrickayoup** [comment]
I don't have the entitlements to do that. I am not the project owner, I simply contributed once in the past. This is all up to @cluther

**Comment by oscarmorrison** [comment]
@cluther What do you think?

**Comment by cluther** [comment]
In 1.0.5 release. Thanks!

**Pull request merged**
